# Banco — Railway vai injetar essas variáveis automaticamente
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Groq
langchain4j.open-ai.chat-model.api-key=${GROQ_API_KEY}
langchain4j.open-ai.chat-model.base-url=https://api.groq.com/openai/v1
langchain4j.open-ai.chat-model.model-name=llama-3.3-70b-versatile
langchain4j.open-ai.chat-model.temperature=0.1

# Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.application.name=triagem-hospitalar
server.port=${PORT:8080}